### ISSUE TITLE
alex-3.1.5 breaks gtk2hs-buildtools

### ISSUE THREAD

**Issue by cmaeder** [simonmar/alex#76]
the upload of alex-3.1.5 http://hackage.haskell.org/package/alex
broke our travis builds https://travis-ci.org/spechub/Hets/builds

```
Failed to install gtk2hs-buildtools-0.13.0.4
Last 10 lines of the build log (
/home/travis/.cabal/logs/gtk2hs-buildtools-0.13.0.4.log ):
[23 of 41] Compiling CAttrs           ( c2hs/c/CAttrs.hs,
dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/CAttrs.o )
[24 of 41] Compiling CBuiltin         ( c2hs/c/CBuiltin.hs,
dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/CBuiltin.o )
[25 of 41] Compiling CParserMonad     ( c2hs/c/CParserMonad.hs,
dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/CParserMonad.o )
[26 of 41] Compiling CLexer           (
dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/CLexer.hs,
dist/build/gtk2hsC2hs/gtk2hsC2hs-tmp/CLexer.o )
c2hs/c/CLexer.x:400:49:
    Not in scope: ‘ord’
    Perhaps you meant one of these:
      ‘odd’ (imported from Prelude), ‘or’ (imported from Prelude),
      ‘ord#’ (imported from GHC.Exts)
cabal: Error: some packages failed to install:
gtk2hs-buildtools-0.13.0.4 failed during the building phase. The exception
was:
ExitFailure 1
```

Unfortunately, we still rely on the glade package that does not work with ghc-7.10

**Comment by simonmar** [comment]
Can you tell me what the differences between the `.hs` file generated by 3.1.4 and 3.1.5 are?  It looks like perhaps you need to import `Data.Char` in your `.x` file.

**Comment by cmaeder** [comment]
I'm not responsible for gtk2hs-buildtools and cannot change it.

**Comment by cmaeder** [comment]
Did alex-3.1.4 re-export `Data.Char.ord` and alex-3.1.5 no longer does?

**Comment by cmaeder** [comment]
The upload of alex-3.1.6 fixed this issue!

**Comment by cmaeder** [comment]
It seems more likely that the upload of gtk2hs-buildtools-0.13.0.5 fixed our issue. (just for the record)
https://github.com/gtk2hs/gtk2hs/issues/146

**Comment by cmaeder** [comment]
I've actually checked it now: not alex-3.1.6 but gtk2hs-buildtools-0.13.0.5 fixed this issue
